config/routes.rb
Synthetic::Application.routes.draw do
  
  resources :remote_jobs do as_routes end
 
  post 'app_install/remote_jobs' => 'remote_jobs#create'
  post 'app_install/awaiting_remote_processing' => 'remote_jobs#awaiting_remote_processing'
  put  'app_install/starting_remote_processing' => 'remote_jobs#starting_remote_processing'
  put  'app_install/completed_remote_processing' => 'remote_jobs#completed_remote_processing'
  
 
  resources :containers
  match '/containers', :to => 'containers#index', :via => :get, :as =>"containers"
  match '/containers/shiny', :to => 'containers#shiny', :via => :get, :as =>"containers_shiny"  
  match '/containers/renew', :to => 'containers#renew', :via => :get, :as =>"containers_renew"  

  resources :shiny_dockers do as_routes end
  resources :sessions do as_routes end
  resources :admins do as_routes end
  resources :users do as_routes end

  resources :verify_jobs
  match "/stream_verification_residual_png" => "verify_jobs#stream_verification_residual_png", :via => :get, :as =>"verify_jobs"
  match "/stream_synthetic_residual_png" => "verify_jobs#stream_synthetic_residual_png", :via => :get, :as =>"verify_jobs"

  get "administration/index"

  get "home/index"
  match 'home/logout'=>'home#logout'
  get 'home/log_the_app_install'

  get 'debug' => 'home#debug'

  root :to => 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :displayName, :duid, :netid
end

app/models/remote_job.rb
class RemoteJob < ActiveRecord::Base
  attr_accessible :completeted, :epsilon, :model, :output_unit, :submitted, :syntheticfile, :verificationfile, :opaque_id, :job_submit_token
  
  mount_uploader :verificationfile, VerificationfileUploader
  mount_uploader :syntheticfile, SyntheticfileUploader
  
  def synthetic_residual_image
		if self.syntheticfile.length > 0 then
      s = "<a href='/stream_synthetic_residual_png?the_opaque_job_id=#{self.opaque_id}' target='_blank'> 
			<img src='/stream_synthetic_residual_png?the_opaque_job_id=#{self.opaque_id}' style='width:304px;height:228px;'></a>"
      return s.html_safe
		else
		  return "-"
		end
  end
  
  def verification_residual_image
		if self.verificationfile.length > 0 then
      s = "<a href='/stream_verification_residual_png?the_opaque_job_id=#{self.opaque_id}' target='_blank'> 
			<img src='/stream_verification_residual_png?the_opaque_job_id=#{self.opaque_id}' style='width:304px;height:228px;'></a>"
      return s.html_safe
		else
		  return "-"
		end
    
  end
  
end

app/models/session.rb
class Session < ActiveRecord::Base
  attr_accessible :action, :netid, :notes
end

app/models/shiny_docker.rb
class ShinyDocker < ActiveRecord::Base
  attr_accessible :appdesc, :appname, :expired, :host, :netid, :port, :pw, :job_submit_token
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :displayName, :duid, :netid
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_filter :onlyAdmin
  layout 'admin_base'
  active_scaffold :"admin" do |conf|
  end
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  
  before_filter :authorize
  
  require 'rest_client'
  
  def docker_app_types
    return ShinyDocker.select("DISTINCT appname, appdesc").order(:appname).reverse
  end
  
  def index
    @user = User.find_by_netid session[:user_id]
    @user_app_collection = []
    docker_app_types.each do |app_type|
      reserved_instance = ShinyDocker.find_by_netid_and_appname(@user.netid, app_type.appname) 
      if reserved_instance.nil? then
        @user_app_collection.push(:container_type=>app_type.appname, :container_desc=> app_type.appdesc, 
        :app_path=> "containers/#{app_type.appname.downcase}",
        :first_visit=> true )
      else # they already have a reserved instance
        @user_app_collection.push(:container_type=>app_type.appname, :container_desc=> app_type.appdesc, 
        :app_path=> "containers/#{app_type.appname.downcase}",
        :app_expired=> reserved_instance.expired,
        :first_visit=> false )
      end     
    end    
    respond_to do |format|
      format.html # index.html.erb
    end
    
  end

  def renew
    user = User.find_by_netid session[:user_id]
    containertype = params[:containertype]
    
    expired_instance = ShinyDocker.find_by_netid_and_appname(user.netid, containertype) 
    expired_instance.expired = false
    expired_instance.save

    #ActivityLog.log(session[:user_id], 'Docker renew',"Docker: #{user.netid} renewed #{containertype} at #{expired_instance.host}:#{expired_instance.port}" )                
  end

  def show
    user = User.find_by_netid session[:user_id]
    container_type = request.path.split("/").last
    if container_type == 'renew' then
      self.renew
    else
      @first_visit = true
      reserved_instance = ShinyDocker.find(:first, :conditions=> ["netid = ? and lower(appname) = ?", user.netid, container_type])
      if reserved_instance.nil? then # they have never reserved an instance
        new_instance = ShinyDocker.find_by_netid_and_appname(nil, container_type)
        if new_instance.nil? then 
            logger.error "Failed to reserve Docker #{container_type} instance for user: #{user.netid}"
            flash[:error] = "ERROR: Cannot find an unused Docker container for #{container_type}"
            redirect_to "/containers" and return
        else
          # reserve this instance
          new_instance.netid = user.netid
          new_instance.save
            
          @docker_host = new_instance.host
          @docker_port = new_instance.port
          @docker_guest_pw = new_instance.pw  
          Session.create(:action => 'container reservation', :netid => user.netid, 
            :notes => "Docker: #{user.netid} reserved #{container_type} at #{@docker_host}:#{@docker_port}")                
        end
      else #send them to the instance they previously reserved
        @first_visit = false
        @docker_host = reserved_instance.host
        @docker_port = reserved_instance.port
        @docker_guest_pw = reserved_instance.pw    
      end 
      if container_type == 'shiny'           
        # shiny-specific code here 
      end
      Session.create(:action => 'container login', :netid => user.netid, 
        :notes => "Docker: #{user.netid} login #{container_type} at #{@docker_host}:#{@docker_port}")                
    end
    render :template => "containers/#{container_type.downcase}" 
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  

  layout "home"
  
  def index
  end
  
  def logout
     reset_session
     return_to_me = "?returnto=" + url_for(:controller=>'home')
     redirect_to "/Shibboleth.sso/Logout?return=https://shib.oit.duke.edu/cgi-bin/logout.pl" +
       CGI.escape(return_to_me)
   end
   
   
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :onlyAdmin
  layout 'admin_base'
  
  active_scaffold :"session" do |conf|
    conf.label = 'Sessions and Activity'
    conf.actions = [:list, :search, :show]
    active_scaffold_config.search.live = true   #submit search terms as we type for more feedback
    conf.list.sorting = { :id => :desc}
    conf.columns = [ :id, :netid, :action,  :notes, :updated_at, :created_at ]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :onlyAdmin
  layout 'admin_base'
  
  active_scaffold :"user" do |conf|
  end
end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/remote_jobs_helper.rb
module RemoteJobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shiny_dockers_helper.rb
module ShinyDockersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/verify_jobs_helper.rb
module VerifyJobsHelper
end

app/views/layouts/admin_base.html.erb
<% content_for :navbar do %>
	<%= render template: 'layouts/admin_menu'%>
<% end %>
<%= render :template => 'layouts/base' %>

app/views/layouts/admin_menu.html.erb
<div>
	<ul class="nav nav-tabs">
	  <li role="presentation" <% if params[:controller] == "admins" %>class="active"<% end %> >
			<%= link_to "Admins", admins_path %> 
		</li>
	  <li <% if params[:controller] == 'users' %>class="active"<% end %> >
			<%= link_to "Users", '/users' %>
	   </li>
 	  <li <% if params[:controller] == 'remote_jobs' %>class="active"<% end %> >
 			<%= link_to "Remote jobs", '/remote_jobs' %>
 	   </li>
	  <li <% if params[:controller] == 'sessions' %>class="active"<% end %> >
			<%= link_to "Sessions", '/sessions' %>
	   </li>
	  <li <% if params[:controller] == 'shiny_dockers' %>class="active"<% end %> >
			<%= link_to "Shiny containers", '/shiny_dockers' %>
	   </li>
	</ul>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Synthetic</title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" /> 
	<meta name="apple-mobile-web-app-capable" content="yes" />
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
	<%= stylesheet_link_tag "style", :media => "all" %>
	
	<%= yield :stylesheets %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Droid+Sans:400,700|Droid+Serif:400,700' rel='stylesheet' type='text/css'>
</head>

<body class="home page page-id-4 page-template-default single-author">
<div id="page" class="hfeed">

<header id="branding" role="banner">
	<div id="logo">
		 <p><a href="http://www.duke.edu" tabindex="1" accesskey="1"><img src="/assets/struct/logo.png" width="141" height="64" alt="Duke University" /></a></p>
     <h1><a href="/" rel="home" tabindex="2" accesskey="2">Synthetic</a></h1>
	<ul id="mmenu">
	  <li <% if params[:controller] == "home"  %>class="active"<% end %> >
			<a href='/'>Home	</a>
		</li>
	  <li <% if params[:controller] == "containers"  %>class="active"<% end %> >
			<a href='/containers'>Create_Model	</a>
		</li>
	  <li <% if params[:controller] == "verify_jobs"  %>class="active"<% end %> >
			<a href='/verify_jobs'>Verify_Model	</a>
		</li>
		<% if session[:is_admin] %>
	  <li <% if params[:controller] == "administration"  %>class="active"<% end %> >
			<a href='/administration/index'>Admin	</a>
		</li>
		<% end %>
		<li class='logout'>
			<a href='/home/logout'>Logout</a>
		</li>
			
	</ul>	
</div>
</header><!-- #branding -->

<%= yield :meat %>

</div>
<div id="subFooter">
  <ul class="links" id="socialLinks">
    <li><a href="http://futurity.org"><img src="/assets/futurity.gif" /></a></li>
    <li><a href="http://www.youtube.com/duke"><img src="/assets/youtube.gif" /></a></li>
    <li><a href="http://twitter.com/DukeNews"><img src="/assets/twitter.gif" /></a></li>
    <li><a href="http://www.facebook.com/DukeUniv"><img src="/assets/facebook.gif" /></a></li>
    <li><a href="http://itunes.duke.edu/"><img src="/assets/apple.gif" /></a></li>
    <li><a href="http://news.duke.edu/"><img src="/assets/rss.gif" /></a></li>
  </ul>
<ul class="links" id="subFootLinks"><li class="menu-334 first"><a href="http://www.access.duke.edu/" title="">Accessibility</a></li>
  <li class="menu-115"><a href="http://duke.edu/styleguide.html" title="">Style Guide</a></li>
  <li class="menu-293"><a href="http://duke.edu/about_this_site.html" title="">About Duke.edu</a></li>
  <li class="menu-116 last"><a href="http://oit.duke.edu/about/contact/index.php" title="">Contact Us</a></li>
</ul>
    <a href="http://www.duke.edu" id="subFootLogo">Duke University</a>
    <p>&copy; 2012-2016 Duke University, Durham, NC 27708 | (919) 684-8111</p>    
</div>

</body>
</html>

app/views/layouts/base.html.erb
<% content_for :meat do %>
	<div id="pagewrapper">
		<div class="entry-content">
			<div id='message_area' style='clear:both;'>
				<% flash.each do |name, msg| -%>
					<%= content_tag :div, msg, class: name %>
		    <% end -%>
			</div>
			<%= yield :navbar%>
			<%= yield %>
  		<div class="clear"></div>
<% end %>

<%= render :template => 'layouts/application' %>

app/views/layouts/home.html.erb
<% content_for :meat do %>
	<div id="main" class="clearfix">
		<div id="mask"></div>

			<div id="primary" class="full-width">
				<div id="content" role="main">
					<div class="front-page">	    
						<div class="clearfix">
							<% flash.each do |name, msg| -%>
							      <%= content_tag :div, msg, class: name %>
							    <% end -%>
									<div class="entry-content">
<%= yield %>


            </div><!--! end of .clearfix -->
					</div><!--! end of .front-page -->
				</div><!-- #content -->
			</div><!-- #primary -->
		</div><!-- #main -->


<% end %>


<%= render :template => 'layouts/application' %>

app/views/layouts/minimalist.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Synthetic</title>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
	
<%= yield :meat %>


</body>
</html>